[www]
; ------------------------------------------------------------------------------
; POOL 'www': Bloque principal de configuración para este conjunto de procesos PHP
; ------------------------------------------------------------------------------

; user y group definen bajo qué usuario y grupo del sistema operativo se 
; ejecutarán los procesos de PHP (y por extensión, WordPress).
; Usar 'nobody' es una excelente práctica de seguridad en Alpine, ya que 
; es un usuario con los privilegios e iteracciones estrictamente mínimos.
user = nobody
group = nobody

; ------------------------------------------------------------------------------
; RED Y CONECTIVIDAD
; ------------------------------------------------------------------------------
; 'listen' indica en qué IP y puerto debe escuchar peticiones el demonio PHP-FPM.
; Poner 0.0.0.0 es crítico: le indica que escuche en TODAS las IPs del contenedor,
; permitiendo que el contenedor NGINX (que está en la misma red de Docker) llegue
; exitosamente mediante FastCGI a este puerto 9000.
; FastCGI es un protocolo que permite a NGINX delegar la ejecución de scripts PHP 
; a este servicio PHP-FPM, lo que es esencial para que WordPress funcione correctamente.
listen = 0.0.0.0:9000

; ------------------------------------------------------------------------------
; PROCESS MANAGER (Gestor de Procesos en Segundo Plano)
; ------------------------------------------------------------------------------
; 'pm' (Gestor de procesos). 'dynamic' significa que el número de procesos 
; hijos activos que manejan las solicitudes fluctuará dinámicamente según el tráfico.
pm = dynamic

; Número máximo absoluto de procesos hijos (límite duro para evitar desborde de RAM).
pm.max_children = 25

; Número de procesos hijos iniciales que arrancan de base (debe ser mayor que min y menor que max).
pm.start_servers = 5

; Límite inferior y superior de procesos 'desocupados' (spare) esperando peticiones.
; FPM gestionará que siempre haya este remanente listo para recibir las oleadas de tráfico WP.
pm.min_spare_servers = 1
pm.max_spare_servers = 10

; ------------------------------------------------------------------------------
; ENTORNO (VARIABLES)
; ------------------------------------------------------------------------------
; clear_env = no es MÁGICO para este proyecto.
; Por defecto, PHP-FPM vacía (limpia) todas las variables de entorno de su proceso por seguridad.
; Si no forzamos el 'no', PHP (y nuestro config wp-cli) sería ciego ante las variables MYSQL_*
; de credenciales que inyectamos desde nuestro fichero base '.env' mediante docker-compose.
clear_env = no